CREATE VIEW dbo.view_vop_ecs_indicadores
AS 
	SELECT DISTINCT 
		AGRP_CNPJ.CNPJ_RAIZ,
		AGRP_TRANS.DT_TRANSACAO,
		CASE WHEN HIST_MDR.indicador = 'I'
			THEN NULL
			ELSE SUM(ISNULL(AGRP_TRANS.VALOR,0)) END
			AS VALOR_DIA,
		HIST_MDR.indicador,
		CAMP.DESCRICAO,
		CAMP_EST.NUMERO_PERIODO,
		HIST_MDR.MDR,
		INDC.HEX_COR
		FROM dbo.agrupamento_transacoes_por_ec AGRP_TRANS
			INNER JOIN view_agrup_cnpj_raiz AGRP_CNPJ
				ON AGRP_TRANS.IID = AGRP_CNPJ.IID
				AND AGRP_TRANS.MID = AGRP_CNPJ.MID
			INNER JOIN campanha_estabelecimento CAMP_EST 
				ON AGRP_TRANS.IID = CAMP_EST.IID
				AND AGRP_TRANS.MID = CAMP_EST.MID
			INNER JOIN campanhas CAMP
				ON CAMP.ID_CAMPANHA = CAMP_EST.ID_CAMPANHA
			INNER JOIN historico_mdr HIST_MDR
				ON HIST_MDR.IID = CAMP_EST.IID
				AND HIST_MDR.MID = CAMP_EST.MID
			INNER JOIN indicadores INDC
				ON INDC.ID_INDICADOR = CAMP_EST.INDICADOR
			INNER JOIN periodos_por_campanha P_CAMP
				ON	P_CAMP.ID_CAMPANHA = CAMP_EST.ID_CAMPANHA
				AND P_CAMP.NUMERO_PERIODO = CAMP_EST.NUMERO_PERIODO 
		WHERE (
			(CAMP_EST.NUMERO_PERIODO = (SELECT TOP 1 NUMERO_PERIODO FROM periodos_por_campanha WHERE ID_CAMPANHA = P_CAMP.ID_CAMPANHA ORDER BY NUMERO_PERIODO DESC)
			 AND AGRP_TRANS.DT_TRANSACAO BETWEEN DATEADD(DAY, (((P_CAMP.NUMERO_PERIODO - 1)*(SELECT DISTINCT QUANTIDADE_DIAS FROM periodos_por_campanha WHERE NUMERO_PERIODO = P_CAMP.NUMERO_PERIODO - 1)) - P_CAMP.QUANTIDADE_DIAS), CAMP_EST.DT_INICIO) AND HIST_MDR.DT_ALTER) 
		OR 
			AGRP_TRANS.DT_TRANSACAO BETWEEN DATEADD(DAY, ((P_CAMP.NUMERO_PERIODO*P_CAMP.QUANTIDADE_DIAS) - P_CAMP.QUANTIDADE_DIAS), CAMP_EST.DT_INICIO) AND HIST_MDR.DT_ALTER)
	GROUP BY AGRP_CNPJ.CNPJ_RAIZ, AGRP_TRANS.DT_TRANSACAO, CAMP.DESCRICAO, CAMP_EST.NUMERO_PERIODO, HIST_MDR.indicador, HIST_MDR.MDR, INDC.HEX_COR
GO
